name: Publish data_structure to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Validate Maven configuration
        run: ./mvnw validate

      - name: Run tests
        run: ./mvnw clean test

      - name: Build library
        run: ./mvnw clean compile package -DskipTests

      - name: Publish to GitHub Packages
        run: ./mvnw deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this Release
            - data_structure library version ${{ github.ref_name }}
            - Compatible with kerbs-operations backend
            
            ## Installation
            Add to your pom.xml:
            ```xml
            <dependency>
                <groupId>org.kerbs_common</groupId>
                <artifactId>data_structure</artifactId>
                <version>${{ github.ref_name }}</version>
            </dependency>
            ```
          draft: false
          prerelease: false